### ISSUE TITLE
🪳 BUG - Game over screen does not display after reloading

### ISSUE THREAD

**Issue by austintirrell** [TirrellStudios/scrmbl#32]

**Comment by CalebQ42** [comment]
The problem is that the localstorage value is retrieved within the `getDailyScmbl` callback which causes those values to populate _after_ the UI is drawn, One of the changes I made was to show only the welcome screen _or_ the game over dialog which seems to have surfaced this issue. Reverting back to how it was previously technically fixes the issue, but the Welcome dialog still flashes up for a moment before the game over dialog shows up.

It should be fairly simple to fix, I just have to move some of the logic that happens within the `getDailyScrmbl` callback to the main thread.
